version: '3'
services:
  demo-app:
    build: .
    volumes:
      - .dockerenv:/src/.venv
      - .:/src 
    ports:
      - 8000:8000 
  db:
    image: mysql:8.0
    platform: linux/x86_64
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes" # root account without password
      MYSQL_DATABASE: "demo" 
      TZ: "Asia/Tokyo"
    volumes: 
      - mysql_data:/var/lib/mysql 
    # MySQL8.0ではデフォルトが"caching_sha2_password"で、ドライバが非対応のため変更
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 33306:3306 # 
volumes:
  mysql_data: